theme: minima
title: Learning GitHub
author: InvictusImperium
email: dwynmiller@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome blog!  It has absolutely nothing in it!  I am just learning GitHub and it is way too early on a Saturday.  
  Also, it is an intenational break in the BPL.  GO GUNNERS!!!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  InvictusImperium

show_excerpts: true # set to false to remove excerpts on the homepage
